site_name: napari-spectrum
site_description: A simple plugin to use with napari
site_author: Giorgia 

theme: readthedocs


repo_url: https://github.com/GiorgiaTortora/napari-spectrum

pages:
- Home: index.md
